(() => {
  const db = window.supabase.createClient(window.BARAN_SUPABASE_URL, window.BARAN_SUPABASE_KEY);
  const $ = s => document.querySelector(s);
  const esc = s => String(s ?? '').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  let products=[], orders=[], categories=[], scents=[];
  let editingId=null;

  async function session(){
    const {data:{session}}=await db.auth.getSession();
    if(!session){ showAuth(); return null; }
    const {data:p,error}=await db.from('admin_profiles').select('*').eq('id',session.user.id).eq('active',true).maybeSingle();
    if(error||!p){ await db.auth.signOut(); showAuth('This account is not an authorized Baran admin.'); return null; }
    $('#adminEmail').textContent=session.user.email||''; $('#auth').classList.add('hidden'); $('#app').classList.remove('hidden'); return session;
  }
  function showAuth(msg=''){ $('#auth').classList.remove('hidden'); $('#app').classList.add('hidden'); if(msg) $('#authMsg').textContent=msg; }
  async function loadAll(){
    const [p,o,c,s,cat]=await Promise.all([
      db.from('products').select('*, categories(slug,name_english), scents(name_english)').order('created_at',{ascending:false}),
      db.from('orders').select('*').order('created_at',{ascending:false}),
      db.from('customers').select('*').order('created_at',{ascending:false}),
      db.from('scents').select('*').order('name_english'),
      db.from('categories').select('*').order('sort_order')
    ]);
    products=p.data||[];orders=o.data||[];scents=s.data||[];categories=cat.data||[];
    $('#customerCount').textContent=(c.data||[]).length; $('#productCount').textContent=products.length; $('#orderCount').textContent=orders.length;
    $('#salesTotal').textContent=(orders.filter(x=>x.status!=='cancelled').reduce((a,x)=>a+Number(x.total||0),0)).toFixed(2)+' USD';
    renderProducts();renderOrders();renderCustomers(c.data||[]);renderSelects();
  }
  function renderProducts(){ $('#productsBody').innerHTML=products.map(p=>`<tr><td><div class="prod"><img src="${esc(p.image_url||'')}" onerror="this.style.display='none'"><span>${esc(p.name_english)}</span></div></td><td>${esc(p.categories?.name_english||'—')}</td><td>${Number(p.price).toFixed(2)}</td><td>${p.stock}</td><td>${p.active?'Active':'Hidden'}</td><td><button class="small" data-edit="${p.id}">Edit</button><button class="small danger" data-del="${p.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No products yet.</td></tr>'; }
  function renderOrders(){ $('#ordersBody').innerHTML=orders.map(o=>`<tr><td><b>${esc(o.order_number)}</b><small>${new Date(o.created_at).toLocaleString()}</small></td><td>${esc(o.customer_name)}<small>${esc(o.customer_phone)}</small></td><td>${Number(o.total).toFixed(2)} ${esc(o.currency)}</td><td><select class="status" data-status="${o.id}">${['pending','confirmed','preparing','shipped','delivered','cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td><td><button class="small" data-view="${o.id}">View</button></td></tr>`).join('')||'<tr><td colspan="5">No orders yet.</td></tr>'; }
  function renderCustomers(cs){ $('#customersBody').innerHTML=cs.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.email||'—')}</td><td>${esc([c.city,c.governorate].filter(Boolean).join(', ')||'—')}</td></tr>`).join('')||'<tr><td colspan="4">No customers yet.</td></tr>'; }
  function renderSelects(){ $('#pCategory').innerHTML=categories.map(c=>`<option value="${c.id}">${esc(c.name_english)}</option>`).join('');$('#pScent').innerHTML='<option value="">No scent</option>'+scents.map(s=>`<option value="${s.id}">${esc(s.name_english)}</option>`).join(''); }
  function openProduct(id=null){ editingId=id; const p=products.find(x=>x.id===id); $('#productModal').classList.add('open'); $('#productTitle').textContent=p?'Edit Product':'New Product'; $('#productForm').reset(); if(p){for(const k of ['slug','name_badini','name_sorani','name_arabic','name_english','description_badini','description_sorani','description_arabic','description_english','wax_type','burn_time_minutes','weight_grams','price','stock','image_url']){if($('#p'+cap(k)))$('#p'+cap(k)).value=p[k]??'';} $('#pCategory').value=p.category_id||'';$('#pScent').value=p.scent_id||'';$('#pFeatured').checked=!!p.featured;$('#pNew').checked=!!p.new_arrival;$('#pBest').checked=!!p.bestseller;$('#pActive').checked=!!p.active;} else {$('#pActive').checked=true;} }
  const cap=k=>k.charAt(0).toUpperCase()+k.slice(1);
  async function saveProduct(e){e.preventDefault();const g=n=>$('#p'+cap(n))?.value||null;const data={slug:g('slug'),name_badini:g('name_badini'),name_sorani:g('name_sorani'),name_arabic:g('name_arabic'),name_english:g('name_english'),description_badini:g('description_badini'),description_sorani:g('description_sorani'),description_arabic:g('description_arabic'),description_english:g('description_english'),category_id:g('category'),scent_id:g('scent')||null,wax_type:g('wax_type'),burn_time_minutes:Number(g('burn_time_minutes')||0)||null,weight_grams:Number(g('weight_grams')||0)||null,price:Number(g('price')||0),stock:Number(g('stock')||0),image_url:g('image_url'),featured:$('#pFeatured').checked,new_arrival:$('#pNew').checked,bestseller:$('#pBest').checked,active:$('#pActive').checked}; const q=editingId?db.from('products').update(data).eq('id',editingId):db.from('products').insert(data);const {error}=await q;if(error){$('#formError').textContent=error.message;return;}$('#productModal').classList.remove('open');await loadAll();}
  async function deleteProduct(id){if(!confirm('Delete this product?'))return;const {error}=await db.from('products').delete().eq('id',id);if(error)alert(error.message);else loadAll();}
  async function status(id,val){const patch={status:val};if(val==='confirmed')patch.confirmed_at=new Date().toISOString();if(val==='shipped')patch.shipped_at=new Date().toISOString();if(val==='delivered')patch.delivered_at=new Date().toISOString();const {error}=await db.from('orders').update(patch).eq('id',id);if(error)alert(error.message);else loadAll();}
  function viewOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;alert(`Order ${o.order_number}\n\nCustomer: ${o.customer_name}\nPhone: ${o.customer_phone}\nAddress: ${o.address||'—'}\nCity: ${o.city||'—'}\nTotal: ${o.total} ${o.currency}\nStatus: ${o.status}\n\nNotes: ${o.customer_notes||'—'}`);}
  async function saveSettings(e){e.preventDefault();const data={site_name:$('#sName').value,phone:$('#sPhone').value,email:$('#sEmail').value,address:$('#sAddress').value,currency:$('#sCurrency').value,delivery_fee:Number($('#sDelivery').value||0),free_delivery_minimum:Number($('#sFree').value||0)||null,whatsapp_number:$('#sWhatsapp').value,instagram_url:$('#sInstagram').value,facebook_url:$('#sFacebook').value,tiktok_url:$('#sTiktok').value};const {data:old}=await db.from('settings').select('id').limit(1).maybeSingle();const r=old?await db.from('settings').update(data).eq('id',old.id):await db.from('settings').insert(data);if(r.error)alert(r.error.message);else alert('Settings saved.');}
  async function loadSettings(){const {data}=await db.from('settings').select('*').limit(1).maybeSingle();if(!data)return;for(const [k,v] of Object.entries({sName:data.site_name,sPhone:data.phone,sEmail:data.email,sAddress:data.address,sCurrency:data.currency,sDelivery:data.delivery_fee,sFree:data.free_delivery_minimum,sWhatsapp:data.whatsapp_number,sInstagram:data.instagram_url,sFacebook:data.facebook_url,sTiktok:data.tiktok_url}))if($('#'+k))$('#'+k).value=v??'';}
  function wire(){ $('#loginForm').onsubmit=async e=>{e.preventDefault();$('#authMsg').textContent='Signing in…';const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)$('#authMsg').textContent=error.message;else session();};$('#logout').onclick=async()=>{await db.auth.signOut();showAuth();};$('#newProduct').onclick=()=>openProduct();$('#closeModal').onclick=()=>$('#productModal').classList.remove('open');$('#productForm').onsubmit=saveProduct;$('#saveSettings').onsubmit=saveSettings;document.addEventListener('click',e=>{if(e.target.dataset.edit)openProduct(e.target.dataset.edit);if(e.target.dataset.del)deleteProduct(e.target.dataset.del);if(e.target.dataset.view)viewOrder(e.target.dataset.view);});document.addEventListener('change',e=>{if(e.target.dataset.status)status(e.target.dataset.status,e.target.value);});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');});}
  function start(){wire();session().then(s=>{if(s){loadAll();loadSettings();}})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
