/* BARAN LIVE STORE — Supabase-backed storefront enhancement */
(() => {
  const start = async () => {
    if (!window.supabase || !window.BARAN_SUPABASE_URL || !window.BARAN_SUPABASE_KEY) return;
    const db = window.supabase.createClient(window.BARAN_SUPABASE_URL, window.BARAN_SUPABASE_KEY);
    window.baranDB = db;
    let liveProducts = [];
    let liveCart = JSON.parse(localStorage.getItem('baran_cart') || '[]');
    const esc = s => String(s ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
    const currentLang = () => window.lang || document.querySelector('#language')?.value || 'badini';
    const nameOf = p => p[`name_${currentLang()}`] || p.name_english || p.name_badini || '';
    const money = n => `${Number(n || 0).toFixed(2)} USD`;

    async function loadProducts(){
      const {data,error}=await db.from('products').select('*, categories(*), scents(*)').eq('active',true).order('featured',{ascending:false}).order('created_at',{ascending:false});
      if(error){console.warn(error.message);return;} liveProducts=data||[]; renderLiveProducts(); renderCart();
    }
    function renderLiveProducts(){
      const grid=document.querySelector('#productGrid'); if(!grid)return;
      const q=(document.querySelector('#search')?.value||'').trim().toLowerCase(), f=window.filter||'all';
      let arr=liveProducts.filter(p=>(f==='all'||p.categories?.slug===f)&&(!q||[p.name_badini,p.name_sorani,p.name_arabic,p.name_english].some(x=>(x||'').toLowerCase().includes(q))));
      const sort=document.querySelector('#sort')?.value; if(sort==='low')arr.sort((a,b)=>Number(a.price)-Number(b.price)); if(sort==='high')arr.sort((a,b)=>Number(b.price)-Number(a.price));
      grid.innerHTML=arr.map(p=>`<article class="product-card live-product" data-id="${p.id}"><div class="product-img" style="${p.image_url?`background-image:url('${esc(p.image_url)}');background-size:cover;background-position:center`:''}">${!p.image_url?'<div class="mini-candle"></div>':''}${p.new_arrival?'<span style="position:absolute;top:14px;right:14px;background:#29241f;color:#fff;padding:7px 10px;font-size:8px">NEW</span>':''}</div><div class="product-info"><h3>${esc(nameOf(p))}</h3><div class="product-meta">${esc(p.wax_type||'')} · ${p.burn_time_minutes?Math.round(p.burn_time_minutes/60)+'h':''} · ${esc(p.scents?.name_english||'')}</div><div class="product-bottom"><strong class="price">${money(p.price)}</strong><button class="add live-add" data-id="${p.id}">+</button></div></div></article>`).join('')||'<p style="grid-column:1/-1;padding:30px;text-align:center">No products found.</p>';
    }
    function saveCart(){localStorage.setItem('baran_cart',JSON.stringify(liveCart));renderCart();}
    function renderCart(){const box=document.querySelector('#cartItems');if(!box)return;let total=0,count=0;box.innerHTML=liveCart.map(i=>{const p=liveProducts.find(x=>x.id===i.id)||i.product;const line=Number(p.price)*i.qty;total+=line;count+=i.qty;return `<div style="display:flex;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid #eee"><div style="width:58px;height:68px;background:#e8ded0 url('${esc(p.image_url||'')}') center/cover no-repeat"></div><div style="flex:1"><strong>${esc(nameOf(p))}</strong><small style="display:block">${money(p.price)} × ${i.qty}</small><button data-remove="${p.id}" style="border:0;background:none;color:#9b6b55;cursor:pointer">Remove</button></div><b>${money(line)}</b></div>`}).join('')||'<div style="padding:40px 0;text-align:center">Your cart is empty.</div>';document.querySelector('#cartTotal').textContent=money(total);document.querySelector('#cartCount').textContent=count;}
    function closeDrawer(){document.querySelector('#cartDrawer')?.classList.remove('open');document.querySelector('#overlay')?.classList.remove('open');}
    function openCheckout(){
      if(!liveCart.length){alert('Your cart is empty');return;}
      document.querySelector('#baranCheckout')?.remove();const modal=document.createElement('div');modal.id='baranCheckout';modal.style.cssText='position:fixed;inset:0;z-index:120;background:#29241fee;display:grid;place-items:center;padding:18px;overflow:auto';
      modal.innerHTML=`<div style="background:#fcfaf6;width:min(680px,100%);padding:32px;max-height:94vh;overflow:auto"><div style="display:flex;justify-content:space-between;border-bottom:1px solid #ded5c8;padding-bottom:18px"><div><small style="color:#b89a63;letter-spacing:.18em">BARAN CANDLE ATELIER</small><h2 style="font:400 38px Amiri;margin:5px 0">Checkout</h2></div><button id="closeCheckout" style="border:0;background:none;font-size:28px">×</button></div><form id="baranOrderForm" style="display:grid;gap:13px;margin-top:22px"><input required name="name" placeholder="Full name"><input required name="phone" placeholder="Phone number"><input type="email" name="email" placeholder="Email (optional)"><input name="governorate" placeholder="Governorate"><input name="city" placeholder="City"><textarea required name="address" placeholder="Full delivery address"></textarea><textarea name="notes" placeholder="Order notes / gift message (optional)"></textarea><div id="orderSummary"></div><button class="btn primary" type="submit">Place order</button><p id="orderResult"></p></form></div>`;document.body.appendChild(modal);document.querySelector('#closeCheckout').onclick=()=>modal.remove();
      let total=0;document.querySelector('#orderSummary').innerHTML=liveCart.map(i=>{const p=liveProducts.find(x=>x.id===i.id)||i.product,v=Number(p.price)*i.qty;total+=v;return `<div style="display:flex;justify-content:space-between;padding:4px 0"><span>${esc(nameOf(p))} × ${i.qty}</span><b>${money(v)}</b></div>`}).join('')+`<hr><b>Total ${money(total)}</b>`;
      document.querySelector('#baranOrderForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),result=document.querySelector('#orderResult');result.textContent='Sending order…';const customer={name:f.get('name'),phone:f.get('phone'),email:f.get('email')||null,governorate:f.get('governorate')||null,city:f.get('city')||null,address:f.get('address'),notes:f.get('notes')||null};const {data:c,error:ce}=await db.from('customers').insert(customer).select().single();if(ce){result.textContent='Could not create customer.';return;}const {data:o,error:oe}=await db.from('orders').insert({customer_id:c.id,customer_name:c.name,customer_phone:c.phone,customer_email:c.email,governorate:c.governorate,city:c.city,address:c.address,customer_notes:c.notes,subtotal:total,total:total,currency:'USD'}).select().single();if(oe){result.textContent='Could not create order.';return;}const items=liveCart.map(i=>{const p=liveProducts.find(x=>x.id===i.id)||i.product;return{order_id:o.id,product_id:p.id,product_name:nameOf(p),scent_name:p.scents?.name_english||null,quantity:i.qty,unit_price:p.price,total_price:Number(p.price)*i.qty};});const{error:ie}=await db.from('order_items').insert(items);if(ie){result.textContent='Order created but items failed.';return;}liveCart=[];saveCart();result.innerHTML=`<strong>Order ${esc(o.order_number)} received.</strong><br>We will contact you on ${esc(c.phone)} to confirm.`;e.target.querySelector('button[type=submit]').disabled=true;};
    }
    document.addEventListener('click',e=>{const add=e.target.closest('.live-add');if(add){const p=liveProducts.find(x=>x.id===add.dataset.id);if(!p)return;const old=liveCart.find(x=>x.id===p.id);old?old.qty++:liveCart.push({id:p.id,qty:1,product:p});saveCart();document.querySelector('#cartDrawer')?.classList.add('open');document.querySelector('#overlay')?.classList.add('open');}const rm=e.target.closest('[data-remove]');if(rm){liveCart=liveCart.filter(x=>x.id!==rm.dataset.remove);saveCart();}});
    document.querySelector('#checkout')?.addEventListener('click',openCheckout);document.querySelector('#closeCart')?.addEventListener('click',closeDrawer);document.querySelector('#overlay')?.addEventListener('click',closeDrawer);document.querySelector('#search')?.addEventListener('input',renderLiveProducts);document.querySelector('#sort')?.addEventListener('change',renderLiveProducts);document.querySelector('#language')?.addEventListener('change',()=>setTimeout(renderLiveProducts,20));document.addEventListener('click',e=>{if(e.target.closest('.filter'))setTimeout(renderLiveProducts,30);});
    await loadProducts();
  }; if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();