/* Baran — complete language coverage for every visible storefront label. */
(function(){
  const extra={
    badini:{navRitual:'ڕێوڕەسم',introLabel:'جیهانەکێ بچووک بۆ هەستەکێ مەزن',introTitle:'مۆم تەنێ نیە.<br><em>رۆناهییا ژیانێیە.</em>',introText:'هەر دانەیەک ب دەست هاتیە چێکرن، ب بۆنەکێ کو بیرەوەری دروست دکەت و شێوەیەک کو ل مالا تەدا دژیت.',ritualTitle:'دەمێ مۆم دسوژیت،<br><em>دەم کەمەک راوەستیت.</em>',ritualText:'مۆمێکێ دابنێ، چرایان کەم بکە و بهێلە بۆنەکە مالا تە پڕ بکەت.',step1:'هەڵبژێرە',step2:'دائگرسێنە',step3:'هەست بکە',readStory:'چیرۆکا مە بخوینە ↗',value1:'مومێکی پاک',value1p:'Soy Wax و Beeswax ب هەڵبژاردنەکا ورد.',value2:'بۆنەکا تایبەت',value2p:'بۆنێن هاوسەنگ بۆ هەستەکا قووڵتر.',value3:'پەکەجینگا جوان',value3p:'ئامادەیە بۆ تە یان کەسەکێ تە خۆش.',value4:'دروستکریا ناڤخۆ',value4p:'ب دەست دروستکری ل کوردستان.',lightMoment:'رۆناهی بۆ ساتێ',collectionBadge:'هەڵبژێردی · ٢٠٢٦',categoryScentedSub:'مۆمێن بۆنخۆش',categoryDecorSub:'مۆمێن دیکۆر و ستوونی',categoryGiftsSub:'کۆمەڵێن دیارییێن دەستکرد',admin:'بەڕێوەبەر',shopLink:'فرۆشتن',contactLink:'پەیوەندی'},
    sorani:{navRitual:'ڕیتواڵ',introLabel:'جیهانێکی بچووک بۆ هەستێکی گەورە',introTitle:'مۆم تەنها نییە.<br><em>ڕووناکییەکی ژیانە.</em>',introText:'هەر دانەیەک بە دەست هەڵدەکۆڵرێت، بە بۆنێک کە بیرەوەری دروست دەکات و شێوەیەک کە لە ماڵەکەتدا دەژیت.',ritualTitle:'کاتێک مۆم دەسووتێت،<br><em>کات کەمێک وەستێت.</em>',ritualText:'مۆمێک دابنێ، چرایەکان کەم بکە و با بۆنەکە ماڵەکەت پڕ بکات.',step1:'هەڵیبژێرە',step2:'داگیرسێنە',step3:'هەست بکە',readStory:'چیرۆکەکەمان بخوێنەوە ↗',value1:'مومی پاک',value1p:'Soy Wax و Beeswax بە هەڵبژاردنی ورد.',value2:'بۆنی تایبەت',value2p:'بۆنە هاوسەنگەکان بۆ هەستی قووڵتر.',value3:'پەکەجینگی جوان',value3p:'ئامادەیە بۆ خۆت یان کەسێکی خۆشەویست.',value4:'دروستکراوی ناوخۆ',value4p:'بە دەست دروستکراو لە کوردستان.',lightMoment:'ڕووناکی بۆ ساتێک',collectionBadge:'هەڵبژێردراو · ٢٠٢٦',categoryScentedSub:'مۆمی بۆنخۆش',categoryDecorSub:'مۆمی دیکۆر و ستوونی',categoryGiftsSub:'کۆمەڵەی دیارییە دەستکردەکان',admin:'ئەدمین',shopLink:'فرۆشتن',contactLink:'پەیوەندی'},
    arabic:{navRitual:'الطقس',introLabel:'عالم صغير لشعور كبير',introTitle:'ليست شمعة فقط.<br><em>إنها ضوء الحياة.</em>',introText:'كل قطعة مصبوبة يدوياً بعطر يصنع ذكرى وشكل يعيش في منزلك.',ritualTitle:'عندما تحترق الشمعة،<br><em>يتوقف الوقت قليلاً.</em>',ritualText:'أشعل شمعة، خفّف الأضواء ودع العطر يملأ منزلك.',step1:'اخترها',step2:'أشعلها',step3:'استشعرها',readStory:'اقرأ قصتنا ↗',value1:'شمع نقي',value1p:'شمع الصويا وشمع العسل باختيار دقيق.',value2:'عطر مميز',value2p:'نفحات متوازنة لشعور أعمق.',value3:'تغليف أنيق',value3p:'جاهز لك أو لمن تحب.',value4:'صناعة محلية',value4p:'مصنوع يدوياً في كردستان.',lightMoment:'نور لكل لحظة',collectionBadge:'مختارات · ٢٠٢٦',categoryScentedSub:'شموع معطرة',categoryDecorSub:'شموع ديكور وأعمدة',categoryGiftsSub:'مجموعات هدايا مصنوعة يدوياً',admin:'الإدارة',shopLink:'المتجر',contactLink:'تواصل'},
    english:{navRitual:'Ritual',introLabel:'A small world for a bigger feeling',introTitle:'More than a candle.<br><em>A little light for life.</em>',introText:'Every piece is hand-poured with a fragrance that creates a memory and a form that lives beautifully in your home.',ritualTitle:'When a candle burns,<br><em>time slows down.</em>',ritualText:'Light a candle, dim the lights and let the fragrance fill your home.',step1:'Choose',step2:'Light',step3:'Feel',readStory:'Read our story ↗',value1:'Pure wax',value1p:'Soy Wax and Beeswax, carefully selected.',value2:'Signature scent',value2p:'Balanced notes for a deeper feeling.',value3:'Beautiful packaging',value3p:'Ready for you or someone you love.',value4:'Locally made',value4p:'Handmade in Kurdistan.',lightMoment:'Light the moment',collectionBadge:'CURATED · 2026',categoryScentedSub:'Scented Candles',categoryDecorSub:'Decorative & Pillar Candles',categoryGiftsSub:'Handmade Gift Sets',admin:'Admin',shopLink:'Shop',contactLink:'Contact'}
  };
  const scentMeta={badini:['موم','دەمێ سووتانێ','بۆن'],sorani:['موم','کاتی سووتان','بۆن'],arabic:['الشمع','وقت الاحتراق','العطر'],english:['Wax','Burn time','Fragrance']};
  function apply(){
    if(typeof dict==='undefined'||typeof lang==='undefined')return;
    Object.assign(dict[lang],extra[lang]);
    const d=dict[lang];
    document.querySelectorAll('[data-i18n]').forEach(e=>{if(d[e.dataset.i18n]!==undefined)e.innerHTML=d[e.dataset.i18n]});
    document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>{if(d[e.dataset.i18nPlaceholder]!==undefined)e.placeholder=d[e.dataset.i18nPlaceholder]});
    const navR=document.querySelector('[data-i18n="navRitual"]');if(navR)navR.textContent=d.navRitual;
    const subs=document.querySelectorAll('.category small'); if(subs.length>=3){subs[0].textContent=d.categoryScentedSub;subs[1].textContent=d.categoryDecorSub;subs[2].textContent=d.categoryGiftsSub}
    const badge=document.querySelector('.collection-badge');if(badge)badge.textContent=d.collectionBadge;
    const note=document.querySelector('.visual-note');if(note)note.innerHTML=d.lightMoment.replace(' ','<br>');
    const footerLinks=document.querySelectorAll('.footer-links a');if(footerLinks.length>=3){footerLinks[0].textContent=d.shopLink;footerLinks[1].textContent=d.admin;footerLinks[2].textContent=d.contactLink}
    document.documentElement.lang=lang==='arabic'?'ar':lang==='english'?'en':'ku';document.documentElement.dir=lang==='english'?'ltr':'rtl';
  }
  const old=window.renderText;window.renderText=function(){if(old)old();apply()};
  const select=document.querySelector('#language');if(select)select.addEventListener('change',()=>setTimeout(apply,30));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(apply,80));else setTimeout(apply,80);
})();
