const products=[
{id:1,name:{badini:'Shîrîn Vanilla',sorani:'ڤانیلا شیرین',arabic:'فانيلا حلوة',english:'Sweet Vanilla'},cat:'scented',price:24,burn:'45h',wax:'Soy Wax',notes:'Vanilla · Amber · Musk'},
{id:2,name:{badini:'Amber Oud',sorani:'عودی ئەمبەر',arabic:'عود وعنبر',english:'Amber Oud'},cat:'scented',price:29,burn:'50h',wax:'Soy Wax',notes:'Oud · Amber · Cedar'},
{id:3,name:{badini:'Ivory Pillar',sorani:'ستونی ئیڤۆری',arabic:'شمعة عاجية',english:'Ivory Pillar'},cat:'decor',price:21,burn:'35h',wax:'Beeswax',notes:'Warm Linen · Vanilla'},
{id:4,name:{badini:'Rose Atelier',sorani:'ئەتلیەی گوڵ',arabic:'وردة فاخرة',english:'Rose Atelier'},cat:'scented',price:26,burn:'40h',wax:'Soy Wax',notes:'Rose · Peony · Sandalwood'},
{id:5,name:{badini:'Golden Duo',sorani:'دووانەی زێڕین',arabic:'ثنائي ذهبي',english:'Golden Duo'},cat:'gifts',price:42,burn:'40h each',wax:'Soy Wax',notes:'Amber · Fig · Vanilla'},
{id:6,name:{badini:'Sandstone',sorani:'بەردی خۆڵەمێشی',arabic:'حجر رملي',english:'Sandstone'},cat:'decor',price:27,burn:'48h',wax:'Beeswax',notes:'Sandalwood · Tonka'},
{id:7,name:{badini:'Fig & Cedar',sorani:'هەنجیر و سەدر',arabic:'تين وأرز',english:'Fig & Cedar'},cat:'scented',price:25,burn:'45h',wax:'Soy Wax',notes:'Fig · Cedar · Moss'},
{id:8,name:{badini:'Baran Gift Box',sorani:'بۆکسێکی دیاری باران',arabic:'صندوق هدايا باران',english:'Baran Gift Box'},cat:'gifts',price:55,burn:'50h each',wax:'Soy Wax',notes:'Curated seasonal scents'}];
const dict={badini:{announcement:'گەیاندنا خێرا بۆ هەمی ناڤچەیێن کوردستان ✦',navHome:'سەرەکی',navShop:'بەرهەم',navStory:'چیرۆکا مە',navContact:'پەیوەندی',heroEyebrow:'بە دەست و خۆشەویستی',heroTitle:'رۆناهییەک بۆ<br><em>هەر ساتەکێ.</em>',heroText:'مۆمێن دەستکردێن پریمیۆم، بۆنێن ئارام و دیارییێن جوان ژ بو هەستەکێ تایبەت.',shopNow:'نیها بکڕە',discover:'پتر بزانە',curated:'کۆکراوەیا تایبەت',categoriesTitle:'جیهانا بۆن و جوانیێ',catScented:'مۆمێن بۆنخۆش',catScentedSub:'Scented Candles',catDecor:'مۆمێن دیکۆر',catDecorSub:'Decorative & Pillar',catGifts:'دیارییێن تایبەت',catGiftsSub:'Handmade Gift Sets',ourCollection:'کۆکراوەیا مە',shopTitle:'بەرهەمێن هەڵبژێردی',viewAll:'هەمی ببینە ↗',search:'ل بەرهەمەکی بگەڕێ...',all:'هەمی',scented:'بۆنخۆش',decor:'دیکۆر',gifts:'دیاری',featured:'هەڵبژێردی',low:'نرخ: کەم بۆ زۆر',high:'نرخ: زۆر بۆ کەم',ourStory:'چیرۆکا باران',storyTitle:'ژ دڵێ هاتیە دروستکرن.<br><em>بۆ مالا تە.</em>',storyText:'هەر مۆمێکێ Baran ب دەست هاتیە دروستکرن، ب مومێکی باش و بۆنێکی هاوسەنگ. باوەری مە وایە تشتێن بچووک دکارن هەستێن مەزن دروست بکەن.',statOne:'دەستکرد',statTwo:'دەمێ سووتانێ',statThree:'زمان',newsletterTitle:'بەهارا بۆنێن خۆ ل دەست مەدە.',newsletterText:'ئیمەیڵا خۆ بنڤیسە بۆ کۆمەڵا نوی و ئۆفەرێن تایبەت.',email:'ئیمەیڵا تە',join:'بەشدار بە',yourCart:'سەبەتا تە',subtotal:'کۆی گشتی',checkout:'بۆ پارەدان',footer:'بۆن، رۆناهی، ئارامی.'},
sorani:{announcement:'گەیاندنی خێرا بۆ هەموو ناوچەکانی کوردستان ✦',navHome:'سەرەکی',navShop:'بەرهەمەکان',navStory:'چیرۆکەکەمان',navContact:'پەیوەندی',heroEyebrow:'بە دەست و خۆشەویستی',heroTitle:'ڕووناکییەک بۆ<br><em>هەموو ساتێک.</em>',heroText:'مۆمی دەستکردی پریمیۆم، بۆنە هێمنەکان و دیارییە جوانەکان بۆ هەستێکی تایبەت.',shopNow:'ئێستا بکڕە',discover:'زیاتر بزانە',curated:'کۆکراوەی تایبەت',categoriesTitle:'جیهانی بۆن و جوانی',catScented:'مۆمی بۆنخۆش',catScentedSub:'Scented Candles',catDecor:'مۆمی دیکۆر',catDecorSub:'Decorative & Pillar',catGifts:'دیارییە تایبەتەکان',catGiftsSub:'Handmade Gift Sets',ourCollection:'کۆمەڵەکەمان',shopTitle:'بەرهەمە هەڵبژێردراوەکان',viewAll:'هەمووی ببینە ↗',search:'بۆ بەرهەمێک بگەڕێ...',all:'هەموو',scented:'بۆنخۆش',decor:'دیکۆر',gifts:'دیاری',featured:'هەڵبژێردراو',low:'نرخ: کەم بۆ زۆر',high:'نرخ: زۆر بۆ کەم',ourStory:'چیرۆکی باران',storyTitle:'لە دڵەوە دروستکراوە.<br><em>بۆ ماڵەوەی تۆ.</em>',storyText:'هەر مۆمێکی Baran بە دەست دروست دەکرێت، بە مومێکی باش و بۆنی هاوسەنگ. باوەڕمان وایە شتە بچووکەکان دەتوانن هەستی گەورە دروست بکەن.',statOne:'دەستکرد',statTwo:'کاتی سووتان',statThree:'زمان',newsletterTitle:'بەهاری بۆنەکانت لەدەست مەدە.',newsletterText:'ئیمەیڵەکەت بنووسە بۆ کۆمەڵە نوێکان و ئۆفەرە تایبەتەکان.',email:'ئیمەیڵەکەت',join:'بەشداری بکە',yourCart:'سەبەتەکەت',subtotal:'کۆی گشتی',checkout:'بڕۆ بۆ پارەدان',footer:'بۆن، ڕووناکی، ئارامی.'},
arabic:{announcement:'توصيل سريع إلى جميع أنحاء العراق ✦',navHome:'الرئيسية',navShop:'المنتجات',navStory:'قصتنا',navContact:'تواصل معنا',heroEyebrow:'مصنوع بحب وعناية',heroTitle:'نورٌ لكل<br><em>لحظة.</em>',heroText:'شموع فاخرة مصنوعة يدوياً، بروائح هادئة وهدايا أنيقة تضيف لمسة استثنائية.',shopNow:'تسوق الآن',discover:'اكتشف المزيد',curated:'تشكيلة مختارة',categoriesTitle:'عالم من العطر والجمال',catScented:'شموع معطرة',catScentedSub:'Scented Candles',catDecor:'شموع للديكور',catDecorSub:'Decorative & Pillar',catGifts:'مجموعات هدايا',catGiftsSub:'Handmade Gift Sets',ourCollection:'مجموعتنا',shopTitle:'منتجات مختارة لك',viewAll:'عرض الكل ↗',search:'ابحث عن منتج...',all:'الكل',scented:'معطرة',decor:'ديكور',gifts:'هدايا',featured:'مميزة',low:'السعر: الأقل أولاً',high:'السعر: الأعلى أولاً',ourStory:'قصة باران',storyTitle:'مصنوعة من القلب.<br><em>لمنزلك.</em>',storyText:'كل شمعة من Baran مصنوعة يدوياً من شمع مختار بعناية وعطور متوازنة. نؤمن أن التفاصيل الصغيرة تصنع مشاعر كبيرة.',statOne:'مصنوعة يدوياً',statTwo:'ساعة احتراق',statThree:'لغات',newsletterTitle:'لا تفوّت مواسم العطر.',newsletterText:'أدخل بريدك لمعرفة التشكيلات الجديدة والعروض الخاصة.',email:'بريدك الإلكتروني',join:'اشترك',yourCart:'سلة التسوق',subtotal:'المجموع',checkout:'إتمام الدفع',footer:'عطر، نور، وهدوء.'},
english:{announcement:'Fast delivery across Iraq & Kurdistan ✦',navHome:'Home',navShop:'Shop',navStory:'Our Story',navContact:'Contact',heroEyebrow:'Made by hand, made with love',heroTitle:'A little light for<br><em>every moment.</em>',heroText:'Premium handmade candles, quiet fragrances and beautiful gifts designed to make everyday moments feel special.',shopNow:'Shop now',discover:'Discover more',curated:'The curated edit',categoriesTitle:'A world of scent & beauty',catScented:'Scented Candles',catScentedSub:'Scented Candles',catDecor:'Decorative Candles',catDecorSub:'Decorative & Pillar',catGifts:'Special Gift Sets',catGiftsSub:'Handmade Gift Sets',ourCollection:'Our collection',shopTitle:'The selected pieces',viewAll:'View all ↗',search:'Search products...',all:'All',scented:'Scented',decor:'Decor',gifts:'Gifts',featured:'Featured',low:'Price: low to high',high:'Price: high to low',ourStory:'The Baran story',storyTitle:'Made from the heart.<br><em>For your home.</em>',storyText:'Every Baran candle is hand-poured with carefully selected wax and balanced fragrance. We believe small details can create big feelings.',statOne:'Handmade',statTwo:'Burn hours',statThree:'Languages',newsletterTitle:'Never miss a season of scent.',newsletterText:'Join our notes for new collections and private offers.',email:'Your email',join:'Join us',yourCart:'Your cart',subtotal:'Subtotal',checkout:'Checkout',footer:'Scent, light, serenity.'}};
let lang='badini',cart=[],filter='all';
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function renderText(){document.documentElement.lang=lang==='arabic'?'ar':lang==='english'?'en':'ku';document.documentElement.dir=lang==='english'?'ltr':'rtl';document.body.lang=lang;const d=dict[lang];$$('[data-i18n]').forEach(e=>{if(d[e.dataset.i18n]!==undefined)e.innerHTML=d[e.dataset.i18n]});$$('[data-i18n-placeholder]').forEach(e=>e.placeholder=d[e.dataset.i18nPlaceholder]);renderProducts();renderCart()}
function renderProducts(){let q=$('#search').value.toLowerCase();let arr=products.filter(p=>(filter==='all'||p.cat===filter)&&p.name[lang].toLowerCase().includes(q));const sort=$('#sort').value;if(sort==='low')arr.sort((a,b)=>a.price-b.price);if(sort==='high')arr.sort((a,b)=>b.price-a.price);$('#productGrid').innerHTML=arr.map(p=>`<article class="product-card"><div class="product-img"><div class="mini-candle"></div></div><div class="product-info"><h3>${p.name[lang]}</h3><div class="product-meta">${p.wax} · ${p.burn} · ${p.notes}</div><div class="product-bottom"><span class="price">$${p.price}.00</span><button class="add" onclick="addToCart(${p.id})">+</button></div></div></article>`).join('')||`<p>${lang==='english'?'No products found.':'هیچ بەرهەمێک نەدۆزرایەوە.'}</p>`}
function addToCart(id){const p=products.find(x=>x.id===id);const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});renderCart();toast(lang==='english'?'Added to cart':lang==='arabic'?'تمت الإضافة إلى السلة':'زیادکرا بۆ سەبەتە')}
function renderCart(){const d=dict[lang];$('#cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);$('#cartItems').innerHTML=cart.length?cart.map(x=>{let p=products.find(y=>y.id===x.id);return `<div class="cart-item"><div><h4>${p.name[lang]}</h4><small>$${p.price}.00 × ${x.qty}</small></div><button onclick="removeCart(${p.id})">×</button></div>`}).join(''):`<p style="color:#8c7f73">${lang==='english'?'Your cart is empty.':'سەبەتەکەت بەتاڵە.'}</p>`;$('#cartTotal').textContent='$'+cart.reduce((s,x)=>s+products.find(y=>y.id===x.id).price*x.qty,0).toFixed(2);}
function removeCart(id){cart=cart.filter(x=>x.id!==id);renderCart()};function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function openCart(){ $('#cartDrawer').classList.add('open');$('#overlay').classList.add('show') }function closeCart(){ $('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show') }
$('#language').onchange=e=>{lang=e.target.value;renderText()};$('#search').oninput=renderProducts;$('#sort').onchange=renderProducts;$('#cartButton').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=closeCart;$('#checkout').onclick=()=>toast(lang==='english'?'Checkout is ready for your payment integration.':'سیستەمی پارەدان دەتوانرێت پاشکۆ بکرێت.');$('#newsletter').onsubmit=e=>{e.preventDefault();toast(lang==='english'?'Welcome to Baran Notes ✦':'بەخێربێیت بۆ Baran Notes ✦');e.target.reset()};
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderProducts()});$$('.category').forEach(c=>c.onclick=()=>{filter=c.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));setTimeout(renderProducts,50)});renderText();