/* Baran Candle Shop — one clean storefront runtime */
(() => {
'use strict';
if ('scrollRestoration' in history) history.scrollRestoration='manual';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const products=[
{id:1,name:{badini:'Shîrîn Vanilla',sorani:'ڤانیلا شیرین',arabic:'فانيلا حلوة',english:'Sweet Vanilla'},cat:'scented',price:24,burn:'45h',wax:'Soy Wax',notes:'Vanilla · Amber · Musk'},
{id:2,name:{badini:'Amber Oud',sorani:'عودی ئەمبەر',arabic:'عود وعنبر',english:'Amber Oud'},cat:'scented',price:29,burn:'50h',wax:'Soy Wax',notes:'Oud · Amber · Cedar'},
{id:3,name:{badini:'Ivory Pillar',sorani:'ستونی ئیڤۆری',arabic:'شمعة عاجية',english:'Ivory Pillar'},cat:'decor',price:21,burn:'35h',wax:'Beeswax',notes:'Warm Linen · Vanilla'},
{id:4,name:{badini:'Rose Atelier',sorani:'ئەتلیەی گوڵ',arabic:'وردة فاخرة',english:'Rose Atelier'},cat:'scented',price:26,burn:'40h',wax:'Soy Wax',notes:'Rose · Peony · Sandalwood'},
{id:5,name:{badini:'Golden Duo',sorani:'دووانەی زێڕین',arabic:'ثنائي ذهبي',english:'Golden Duo'},cat:'gifts',price:42,burn:'40h each',wax:'Soy Wax',notes:'Amber · Fig · Vanilla'},
{id:6,name:{badini:'Sandstone',sorani:'بەردی خۆڵەمێشی',arabic:'حجر رملي',english:'Sandstone'},cat:'decor',price:27,burn:'48h',wax:'Beeswax',notes:'Sandalwood · Tonka'},
{id:7,name:{badini:'Fig & Cedar',sorani:'هەنجیر و سەدر',arabic:'تين وأرز',english:'Fig & Cedar'},cat:'scented',price:25,burn:'45h',wax:'Soy Wax',notes:'Fig · Cedar · Moss'},
{id:8,name:{badini:'Baran Gift Box',sorani:'بۆکسێکی دیاری باران',arabic:'صندوق هدايا باران',english:'Baran Gift Box'},cat:'gifts',price:55,burn:'50h each',wax:'Soy Wax',notes:'Curated seasonal scents'}];
const T={
badini:{announcement:'گەهاندنا خێرا بۆ هەمی ناڤچەیێن کوردستان ✦',navHome:'سەرەکی',navShop:'بەرهەم',navRitual:'ڕێوڕەسم',navStory:'چیرۆکا مە',navContact:'پەیوەندی',heroEyebrow:'ب دەست و خۆشەویستی',heroTitle:'رۆناهییەک بۆ<br><em>هەر ساتەکێ.</em>',heroText:'مۆمێن دەستکردێن پریمیۆم، بۆنێن ئارام و دیارییێن جوان ژ بو هەستەکێ تایبەت.',shopNow:'نیها بکڕە',categoriesTitle:'جیهانا بۆن و جوانیێ',catScented:'مۆمێن بۆنخۆش',catScentedSub:'مۆمێن بۆنخۆش',catDecor:'مۆمێن دیکۆر',catDecorSub:'مۆمێن دیکۆر و ستوونی',catGifts:'دیارییێن تایبەت',catGiftsSub:'کۆمەڵێن دیارییێن دەستکرد',ourCollection:'کۆکراوەیا مە',shopTitle:'بەرهەمێن هەڵبژێردی',viewAll:'هەمی ببینە ↗',search:'ل بەرهەمەکی بگەڕێ...',all:'هەمی',scented:'بۆنخۆش',decor:'دیکۆر',gifts:'دیاری',featured:'هەڵبژێردی',low:'نرخ: کەم بۆ زۆر',high:'نرخ: زۆر بۆ کەم',ourStory:'چیرۆکا باران',storyTitle:'ژ دڵێ هاتیە دروستکرن.<br><em>بۆ مالا تە.</em>',storyText:'هەر مۆمێکێ Baran ب دەست هاتیە دروستکرن، ب مومێکی باش و بۆنێکی هاوسەنگ. باوەری مە وایە تشتێن بچووک دکارن هەستێن مەزن دروست بکەن.',ritualTitle:'دەمێ مۆم دسوژیت،<br><em>دەم کەمەک راوەستیت.</em>',ritualText:'مۆمێکێ دابنێ، چرایان کەم بکە و بهێلە بۆنەکە مالا تە پڕ بکەت.',step1:'هەڵبژێرە',step2:'دائگرسێنە',step3:'هەست بکە',value1:'مومێکی پاک',value1p:'Soy Wax و Beeswax ب هەڵبژاردنەکا ورد.',value2:'بۆنەکا تایبەت',value2p:'بۆنێن هاوسەنگ بۆ هەستەکا قووڵتر.',value3:'پەکەجینگا جوان',value3p:'ئامادەیە بۆ تە یان کەسەکێ تە خۆش.',value4:'دروستکریا ناڤخۆ',value4p:'ب دەست دروستکری ل کوردستان.',newsletterTitle:'بەهارا بۆنێن خۆ ل دەست مەدە.',newsletterText:'ئیمەیڵا خۆ بنڤیسە بۆ کۆمەڵا نوی و ئۆفەرێن تایبەت.',email:'ئیمەیڵا تە',join:'بەشدار بە',yourCart:'سەبەتا تە',subtotal:'کۆی گشتی',checkout:'بۆ پارەدان',footer:'بۆن، رۆناهی، ئارامی',readStory:'چیرۆکا مە بخوینە ↗',collectionBadge:'هەڵبژێردی · ٢٠٢٦',lightMoment:'رۆناهی بۆ ساتێ'},
sorani:{announcement:'گەیاندنی خێرا بۆ هەموو ناوچەکانی کوردستان ✦',navHome:'سەرەکی',navShop:'بەرهەمەکان',navRitual:'ڕیتواڵ',navStory:'چیرۆکەکەمان',navContact:'پەیوەندی',heroEyebrow:'بە دەست و خۆشەویستی',heroTitle:'ڕووناکییەک بۆ<br><em>هەموو ساتێک.</em>',heroText:'مۆمی دەستکردی پریمیۆم، بۆنە هێمنەکان و دیارییە جوانەکان بۆ هەستێکی تایبەت.',shopNow:'ئێستا بکڕە',categoriesTitle:'جیهانی بۆن و جوانی',catScented:'مۆمی بۆنخۆش',catScentedSub:'مۆمی بۆنخۆش',catDecor:'مۆمی دیکۆر',catDecorSub:'مۆمی دیکۆر و ستوونی',catGifts:'دیارییە تایبەتەکان',catGiftsSub:'کۆمەڵەی دیارییە دەستکردەکان',ourCollection:'کۆمەڵەکەمان',shopTitle:'بەرهەمە هەڵبژێردراوەکان',viewAll:'هەمووی ببینە ↗',search:'بۆ بەرهەمێک بگەڕێ...',all:'هەموو',scented:'بۆنخۆش',decor:'دیکۆر',gifts:'دیاری',featured:'هەڵبژێردراو',low:'نرخ: کەم بۆ زۆر',high:'نرخ: زۆر بۆ کەم',ourStory:'چیرۆکی باران',storyTitle:'لە دڵەوە دروستکراوە.<br><em>بۆ ماڵەوەی تۆ.</em>',storyText:'هەر مۆمێکی Baran بە دەست دروست دەکرێت، بە مومێکی باش و بۆنی هاوسەنگ. باوەڕمان وایە شتە بچووکەکان دەتوانن هەستی گەورە دروست بکەن.',ritualTitle:'کاتێک مۆم دەسووتێت،<br><em>کات کەمێک وەستێت.</em>',ritualText:'مۆمێک دابنێ، چرایەکان کەم بکە و با بۆنەکە ماڵەکەت پڕ بکات.',step1:'هەڵیبژێرە',step2:'داگیرسێنە',step3:'هەست بکە',value1:'مومی پاک',value1p:'Soy Wax و Beeswax بە هەڵبژاردنی ورد.',value2:'بۆنی تایبەت',value2p:'بۆنە هاوسەنگەکان بۆ هەستی قووڵتر.',value3:'پەکەجینگی جوان',value3p:'ئامادەیە بۆ خۆت یان کەسێکی خۆشەویست.',value4:'دروستکراوی ناوخۆ',value4p:'بە دەست دروستکراو لە کوردستان.',newsletterTitle:'بەهاری بۆنەکانت لەدەست مەدە.',newsletterText:'ئیمەیڵەکەت بنووسە بۆ کۆمەڵە نوێکان و ئۆفەرە تایبەتەکان.',email:'ئیمەیڵەکەت',join:'بەشداری بکە',yourCart:'سەبەتەکەت',subtotal:'کۆی گشتی',checkout:'بڕۆ بۆ پارەدان',footer:'بۆن، ڕووناکی، ئارامی',readStory:'چیرۆکەکەمان بخوێنەوە ↗',collectionBadge:'هەڵبژێردراو · ٢٠٢٦',lightMoment:'ڕووناکی بۆ ساتێک'},
arabic:{announcement:'توصيل سريع إلى جميع أنحاء العراق ✦',navHome:'الرئيسية',navShop:'المنتجات',navRitual:'الطقس',navStory:'قصتنا',navContact:'تواصل معنا',heroEyebrow:'مصنوع بحب وعناية',heroTitle:'نورٌ لكل<br><em>لحظة.</em>',heroText:'شموع فاخرة مصنوعة يدوياً، بروائح هادئة وهدايا أنيقة تضيف لمسة استثنائية.',shopNow:'تسوق الآن',categoriesTitle:'عالم من العطر والجمال',catScented:'شموع معطرة',catScentedSub:'شموع معطرة',catDecor:'شموع للديكور',catDecorSub:'شموع ديكور وأعمدة',catGifts:'مجموعات هدايا',catGiftsSub:'مجموعات هدايا مصنوعة يدوياً',ourCollection:'مجموعتنا',shopTitle:'منتجات مختارة لك',viewAll:'عرض الكل ↗',search:'ابحث عن منتج...',all:'الكل',scented:'معطرة',decor:'ديكور',gifts:'هدايا',featured:'مميزة',low:'السعر: الأقل أولاً',high:'السعر: الأعلى أولاً',ourStory:'قصة باران',storyTitle:'مصنوعة من القلب.<br><em>لمنزلك.</em>',storyText:'كل شمعة من Baran مصنوعة يدوياً من شمع مختار بعناية وعطور متوازنة. نؤمن أن التفاصيل الصغيرة تصنع مشاعر كبيرة.',ritualTitle:'عندما تحترق الشمعة،<br><em>يتوقف الوقت قليلاً.</em>',ritualText:'أشعل شمعة، خفّف الأضواء ودع العطر يملأ منزلك.',step1:'اخترها',step2:'أشعلها',step3:'استشعرها',value1:'شمع نقي',value1p:'شمع الصويا وشمع العسل باختيار دقيق.',value2:'عطر مميز',value2p:'نفحات متوازنة لشعور أعمق.',value3:'تغليف أنيق',value3p:'جاهز لك أو لمن تحب.',value4:'صناعة محلية',value4p:'مصنوع يدوياً في كردستان.',newsletterTitle:'لا تفوّت مواسم العطر.',newsletterText:'أدخل بريدك لمعرفة التشكيلات الجديدة والعروض الخاصة.',email:'بريدك الإلكتروني',join:'اشترك',yourCart:'سلة التسوق',subtotal:'المجموع',checkout:'إتمام الدفع',footer:'عطر، نور، وهدوء.',readStory:'اقرأ قصتنا ↗',collectionBadge:'مختارات · ٢٠٢٦',lightMoment:'نور لكل لحظة'},
english:{announcement:'Fast delivery across Iraq & Kurdistan ✦',navHome:'Home',navShop:'Shop',navRitual:'Ritual',navStory:'Our Story',navContact:'Contact',heroEyebrow:'Made by hand, made with love',heroTitle:'A little light for<br><em>every moment.</em>',heroText:'Premium handmade candles, quiet fragrances and beautiful gifts designed to make everyday moments feel special.',shopNow:'Shop now',categoriesTitle:'A world of scent & beauty',catScented:'Scented Candles',catScentedSub:'Scented Candles',catDecor:'Decorative Candles',catDecorSub:'Decorative & Pillar Candles',catGifts:'Special Gift Sets',catGiftsSub:'Handmade Gift Sets',ourCollection:'Our collection',shopTitle:'The selected pieces',viewAll:'View all ↗',search:'Search products...',all:'All',scented:'Scented',decor:'Decor',gifts:'Gifts',featured:'Featured',low:'Price: low to high',high:'Price: high to low',ourStory:'The Baran story',storyTitle:'Made from the heart.<br><em>For your home.</em>',storyText:'Every Baran candle is hand-poured with carefully selected wax and balanced fragrance. We believe small details can create big feelings.',ritualTitle:'When a candle burns,<br><em>time slows down.</em>',ritualText:'Light a candle, dim the lights and let the fragrance fill your home.',step1:'Choose',step2:'Light',step3:'Feel',value1:'Pure wax',value1p:'Soy Wax and Beeswax, carefully selected.',value2:'Signature scent',value2p:'Balanced notes for a deeper feeling.',value3:'Beautiful packaging',value3p:'Ready for you or someone you love.',value4:'Locally made',value4p:'Hand-poured in Kurdistan.',newsletterTitle:'Never miss a season of scent.',newsletterText:'Join our notes for new collections and private offers.',email:'Your email',join:'Join us',yourCart:'Your cart',subtotal:'Subtotal',checkout:'Checkout',footer:'Scent, light, serenity.',readStory:'Read our story ↗',collectionBadge:'CURATED · 2026',lightMoment:'Light the moment'}};
let lang=localStorage.getItem('baran-language')||'badini'; if(!T[lang])lang='badini'; let filter='all'; let cart=JSON.parse(localStorage.getItem('baran-cart')||'[]');
const tr=k=>T[lang][k]??T.english[k]??k; const safe=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function renderText(){
$$('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(T[lang][k]!==undefined)e.innerHTML=T[lang][k]});
$$('[data-i18n-placeholder]').forEach(e=>{const k=e.dataset.i18nPlaceholder;if(T[lang][k]!==undefined)e.placeholder=T[lang][k]});
$$('[data-i18n-title]').forEach(e=>{const k=e.dataset.i18nTitle;if(T[lang][k]!==undefined)e.title=T[lang][k]});
// Translate legacy hard-coded labels still present in the HTML.
const hard={'.hero-proof span:nth-child(1)':{badini:'١٠٠٪ دەستکرد',sorani:'١٠٠٪ دەستکرد',arabic:'١٠٠٪ مصنوع يدوياً',english:'100% Handmade'},'.hero-proof span:nth-child(2)':{badini:'مومی سویا و مومی زەڕەنگ',sorani:'مومی سویا و مومی زەڕەنگ',arabic:'شمع الصويا وشمع العسل',english:'Soy & Beeswax'},'.hero-proof span:nth-child(3)':{badini:'بۆنی پریمیۆم',sorani:'بۆنی پریمیۆم',arabic:'عطر فاخر',english:'Premium Fragrance'},'.visual-note':{badini:'رۆناهی بۆ ساتێ',sorani:'ڕووناکی بۆ ساتێک',arabic:'نور لكل لحظة',english:'LIGHT THE MOMENT'},'.collection-badge':T[lang],'.story-candle small':{badini:'دروستکراو<br>ب دەست',sorani:'دەست<br>دروستکراو',arabic:'مصنوع<br>يدوياً',english:'HAND<br>POURED'},'.footer-links a:nth-child(1)':{badini:'بەرهەم',sorani:'بەرهەمەکان',arabic:'المنتجات',english:'Shop'},'.footer-links a:nth-child(3)':{badini:'پەیوەندی',sorani:'پەیوەندی',arabic:'تواصل',english:'Contact'}};
Object.entries(hard).forEach(([sel,map])=>{const e=$(sel);if(!e)return;const v=map===T[lang]?tr('collectionBadge'):map[lang];if(v!==undefined)e.innerHTML=v});
if($('#language'))$('#language').value=lang;
document.documentElement.lang=lang==='english'?'en':lang==='arabic'?'ar':'ku';document.documentElement.dir=lang==='english'?'ltr':'rtl';
}
function renderProducts(){const g=$('#productGrid');if(!g)return;const q=($('#search')?.value||'').trim().toLocaleLowerCase();let a=products.filter(p=>filter==='all'||p.cat===filter).filter(p=>!q||Object.values(p.name).some(n=>n.toLocaleLowerCase().includes(q)));const s=$('#sort')?.value;if(s==='low')a.sort((x,y)=>x.price-y.price);if(s==='high')a.sort((x,y)=>y.price-x.price);g.innerHTML=a.map(p=>`<article class="product-card"><div class="product-img"><div class="mini-candle"></div></div><div class="product-info"><h3>${safe(p.name[lang])}</h3><div class="product-meta">${safe(meta(p))}</div><div class="product-bottom"><strong>$${p.price.toFixed(2)}</strong><button class="add" data-add="${p.id}">+</button></div></div></article>`).join('')||`<p>${lang==='english'?'No products found.':lang==='arabic'?'لا توجد منتجات.':'هیچ بەرهەمێک نەدۆزرایەوە.'}</p>`}
function meta(p){const m={badini:{soy:'مومی سویا',bee:'مومی زەڕەنگ'},sorani:{soy:'مومی سویا',bee:'مومی زەڕەنگ'},arabic:{soy:'شمع الصويا',bee:'شمع العسل'},english:{soy:'Soy Wax',bee:'Beeswax'}};const wax=p.wax==='Beeswax'?m[lang].bee:m[lang].soy;const notes={badini:{'Vanilla · Amber · Musk':'ڤانیلا · ئەمبەر · موشک','Oud · Amber · Cedar':'عود · ئەمبەر · سەدر','Warm Linen · Vanilla':'کتانێ گەرم · ڤانیلا','Rose · Peony · Sandalwood':'گوڵ · پێۆنی · دارێ سەندەل'},sorani:{'Vanilla · Amber · Musk':'ڤانیلا · ئەمبەر · موشک','Oud · Amber · Cedar':'عود · ئەمبەر · سەدر','Warm Linen · Vanilla':'کتانی گەرم · ڤانیلا','Rose · Peony · Sandalwood':'گوڵ · پێۆنی · دارستان'},arabic:{'Vanilla · Amber · Musk':'فانيلا · عنبر · مسك','Oud · Amber · Cedar':'عود · عنبر · أرز','Warm Linen · Vanilla':'كتان دافئ · فانيلا','Rose · Peony · Sandalwood':'ورد · بيوني · صندل'},english:{}};return `${wax} · ${p.burn} · ${notes[lang]?.[p.notes]||p.notes}`}
function renderCart(){const n=cart.reduce((a,x)=>a+x.qty,0);if($('#cartCount'))$('#cartCount').textContent=n;const box=$('#cartItems');if(!box)return;box.innerHTML=cart.length?cart.map(i=>{const p=products.find(x=>x.id===i.id);return p?`<div class="cart-row"><div><b>${safe(p.name[lang])}</b><small>$${p.price.toFixed(2)} × ${i.qty}</small></div><div><button class="small-cart" data-dec="${p.id}">−</button><button class="small-cart" data-inc="${p.id}">+</button></div></div>`:''}).join(''):`<div class="empty-cart">${lang==='english'?'Your cart is empty.':lang==='arabic'?'السلة فارغة.':lang==='badini'?'سەبەتا تە ڤالا یە.':'سەبەتەکەت بەتاڵە.'}</div>`;const total=cart.reduce((a,i)=>{const p=products.find(x=>x.id===i.id);return a+(p?p.price*i.qty:0)},0);if($('#cartTotal'))$('#cartTotal').textContent=`$${total.toFixed(2)}`}
function setLanguage(v){if(!T[v])return;lang=v;localStorage.setItem('baran-language',lang);renderText();renderProducts();renderCart()}
function cartChange(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(i=>i.id!==id);localStorage.setItem('baran-cart',JSON.stringify(cart));renderCart()}
function openCart(){$('#cartDrawer')?.classList.add('open');$('#overlay')?.classList.add('show')};function closeCart(){$('#cartDrawer')?.classList.remove('open');$('#overlay')?.classList.remove('show')}
document.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a){const id=+a.dataset.add,x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});localStorage.setItem('baran-cart',JSON.stringify(cart));renderCart();openCart();return}const i=e.target.closest('[data-inc]');if(i){cartChange(+i.dataset.inc,1);return}const d=e.target.closest('[data-dec]');if(d){cartChange(+d.dataset.dec,-1);return}const f=e.target.closest('.filter');if(f){filter=f.dataset.filter||'all';$$('.filter').forEach(x=>x.classList.toggle('active',x===f));renderProducts();return}const c=e.target.closest('.category[data-filter]');if(c){filter=c.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));}});
function init(){if('scrollRestoration'in history)history.scrollRestoration='manual';const nav=performance.getEntriesByType?.('navigation')?.[0];if(nav?.type==='reload'){history.replaceState(null,'',location.pathname+location.search);[0,80,200].forEach(t=>setTimeout(()=>scrollTo(0,0),t))}$('#language')?.addEventListener('change',e=>setLanguage(e.target.value));$('#search')?.addEventListener('input',renderProducts);$('#sort')?.addEventListener('change',renderProducts);$('#cartButton')?.addEventListener('click',openCart);$('#closeCart')?.addEventListener('click',closeCart);$('#overlay')?.addEventListener('click',closeCart);$('#menuBtn')?.addEventListener('click',()=>$('#mobileNav')?.classList.toggle('open'));$('#mobileNav')?.addEventListener('click',()=>$('#mobileNav')?.classList.remove('open'));$('#searchTrigger')?.addEventListener('click',()=>{document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'});setTimeout(()=>$('#search')?.focus(),400)});$('#checkout')?.addEventListener('click',()=>{if(cart.length)location.href='checkout.html'});renderText();renderProducts();renderCart()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();